import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 2 (80ms of deliberate cost per test)

test.describe('load suite 42', { tag: ['@load'] }, () => {
  test('load 42-1: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-2: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-3: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-4: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-5: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-6: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-7: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-8: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-9: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-10: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-11: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-12: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-13: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-14: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-15: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-16: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-17: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-18: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-19: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 42-20: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 42</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 42');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });
});
