import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 1 (40ms of deliberate cost per test)

test.describe('load suite 11', { tag: ['@load'] }, () => {
  test('load 11-1: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-2: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-3: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-4: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-5: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-6: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-7: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-8: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-9: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-10: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-11: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-12: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-13: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-14: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-15: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-16: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-17: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-18: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-19: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });

  test('load 11-20: renders and asserts @load @load-w1', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 11</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 11');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(40);
  });
});
