import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 2 (80ms of deliberate cost per test)

test.describe('load suite 07', { tag: ['@load'] }, () => {
  test('load 07-1: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-2: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-3: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-4: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-5: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-6: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-7: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-8: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-9: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-10: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-11: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-12: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-13: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-14: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-15: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-16: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-17: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-18: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-19: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 07-20: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 07</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 07');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });
});
