import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 2 (80ms of deliberate cost per test)

test.describe('load suite 22', { tag: ['@load'] }, () => {
  test('load 22-1: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-2: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-3: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-4: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-5: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-6: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-7: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-8: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-9: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-10: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-11: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-12: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-13: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-14: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-15: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-16: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-17: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-18: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-19: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 22-20: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 22</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 22');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });
});
