import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 2 (80ms of deliberate cost per test)

test.describe('load suite 12', { tag: ['@load'] }, () => {
  test('load 12-1: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-2: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-3: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-4: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-5: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-6: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-7: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-8: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-9: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-10: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-11: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-12: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-13: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-14: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-15: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-16: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-17: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-18: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-19: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });

  test('load 12-20: renders and asserts @load @load-w2', async ({ page }) => {
    await page.setContent(`<main id="app"><h1>spec 12</h1><ul>${
      Array.from({ length: 8 }, (_, n) => `<li data-item="${n}">item ${n}</li>`).join('')
    }</ul></main>`);
    await expect(page.locator('h1')).toHaveText('spec 12');
    await expect(page.locator('li')).toHaveCount(8);
    await expect(page.locator('[data-item="3"]')).toHaveText('item 3');
    await page.waitForTimeout(80);
  });
});
