import { test, expect } from '@playwright/test';

// GENERATED by scripts/generate-load-tests.js — do not edit by hand.
// weight 5 — 2170ms of simulated latency per test

test.describe('regression suite 078', () => {
  // the flaky cases need one retry to demonstrate recovery
  test.describe.configure({ retries: 1 });

  test('spec 078 · case 1 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer1@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer1@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 2 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer2@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer2@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 3 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer3@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer3@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 4 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer4@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer4@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 5 · cart count regression @regression-load @known-failure', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="1"]');
    await page.waitForTimeout(2170);
    // Intentional: one click was made, the assertion demands three. Deliberate
    // failures keep the failure path exercised on every run.
    await expect(page.getByTestId('cart-count')).toHaveText('3');
  });

  test('spec 078 · case 6 · settles only on retry @regression-load @flaky', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="0"]');
    await expect(page.getByTestId('cart-count')).toHaveText('1');
    await page.waitForTimeout(2170);
    // Fails the first attempt, passes the retry — the flaky path, deterministically.
    expect(test.info().retry, 'first attempt is expected to fail').toBeGreaterThan(0);
  });

  test('spec 078 · case 7 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer7@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer7@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 8 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer8@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer8@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 9 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer9@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer9@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 10 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer10@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer10@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 11 · cart count regression @regression-load @known-failure', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="1"]');
    await page.waitForTimeout(2170);
    // Intentional: one click was made, the assertion demands three. Deliberate
    // failures keep the failure path exercised on every run.
    await expect(page.getByTestId('cart-count')).toHaveText('3');
  });

  test('spec 078 · case 12 · settles only on retry @regression-load @flaky', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="0"]');
    await expect(page.getByTestId('cart-count')).toHaveText('1');
    await page.waitForTimeout(2170);
    // Fails the first attempt, passes the retry — the flaky path, deterministically.
    expect(test.info().retry, 'first attempt is expected to fail').toBeGreaterThan(0);
  });

  test('spec 078 · case 13 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer13@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer13@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 14 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer14@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer14@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 15 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer15@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer15@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 16 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer16@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer16@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 17 · cart count regression @regression-load @known-failure', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="1"]');
    await page.waitForTimeout(2170);
    // Intentional: one click was made, the assertion demands three. Deliberate
    // failures keep the failure path exercised on every run.
    await expect(page.getByTestId('cart-count')).toHaveText('3');
  });

  test('spec 078 · case 18 · settles only on retry @regression-load @flaky', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="0"]');
    await expect(page.getByTestId('cart-count')).toHaveText('1');
    await page.waitForTimeout(2170);
    // Fails the first attempt, passes the retry — the flaky path, deterministically.
    expect(test.info().retry, 'first attempt is expected to fail').toBeGreaterThan(0);
  });

  test('spec 078 · case 19 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer19@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer19@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 20 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer20@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer20@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 21 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer21@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer21@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 22 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer22@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer22@example.com');
    await page.waitForTimeout(2170);
  });

  test('spec 078 · case 23 · cart count regression @regression-load @known-failure', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="1"]');
    await page.waitForTimeout(2170);
    // Intentional: one click was made, the assertion demands three. Deliberate
    // failures keep the failure path exercised on every run.
    await expect(page.getByTestId('cart-count')).toHaveText('3');
  });

  test('spec 078 · case 24 · settles only on retry @regression-load @flaky', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await page.click('[data-add="0"]');
    await expect(page.getByTestId('cart-count')).toHaveText('1');
    await page.waitForTimeout(2170);
    // Fails the first attempt, passes the retry — the flaky path, deterministically.
    expect(test.info().retry, 'first attempt is expected to fail').toBeGreaterThan(0);
  });

  test('spec 078 · case 25 · adds items and updates the cart @regression-load', async ({ page }) => {
    await page.setContent(`
      <main id="app">
        <header><h1>Store 078</h1><span data-testid="cart-count">0</span></header>
        <ul id="catalogue">${Array.from({ length: 6 }, (_, n) =>
          `<li data-sku="sku-${n}"><span class="name">Item ${n}</span>
             <span class="price">$${(n + 1) * 10}</span>
             <button data-add="${n}">Add</button></li>`).join('')}
        </ul>
        <form id="checkout"><input name="email" /><button type="submit">Pay</button></form>
      </main>
      <script>
        let count = 0;
        document.querySelectorAll('[data-add]').forEach(b =>
          b.addEventListener('click', () => {
            document.querySelector('[data-testid="cart-count"]').textContent = ++count;
          }));
      </script>`);
    await expect(page.locator('h1')).toHaveText('Store 078');
    await expect(page.locator('#catalogue li')).toHaveCount(6);
    await page.click('[data-add="2"]');
    await page.click('[data-add="4"]');
    await expect(page.getByTestId('cart-count')).toHaveText('2');
    await page.fill('input[name="email"]', 'buyer25@example.com');
    await expect(page.locator('input[name="email"]')).toHaveValue('buyer25@example.com');
    await page.waitForTimeout(2170);
  });
});
